{
 "title": "Friendli Engine",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (friendli_engine_version)",
     "legendFormat": "Engine Processes ({{version}})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(friendli_responses_total[$__rate_interval]))",
     "legendFormat": "Overall Throughput"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(friendli_current_assigned_items)",
     "legendFormat": "Processing Items"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(friendli_current_waiting_items)",
     "legendFormat": "Waiting Items"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(friendli_requests_total[$__rate_interval])",
     "legendFormat": "Received ({{pod}})"
    },
    {
     "expr": "rate(friendli_responses_total[$__rate_interval])",
     "legendFormat": "Served ({{pod}})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "friendli_requests_latencies{quantile=\"0.99\"}",
     "legendFormat": "P99 ({{pod}})"
    },
    {
     "expr": "friendli_requests_latencies{quantile=\"0.9\"}",
     "legendFormat": "P90 ({{pod}})"
    },
    {
     "expr": "friendli_requests_latencies{quantile=\"0.5\"}",
     "legendFormat": "P50 ({{pod}})"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "friendli_requests_ttft{quantile=\"0.99\"}",
     "legendFormat": "P99 ({{pod}})"
    },
    {
     "expr": "friendli_requests_ttft{quantile=\"0.9\"}",
     "legendFormat": "P90 ({{pod}})"
    },
    {
     "expr": "friendli_requests_ttft{quantile=\"0.5\"}",
     "legendFormat": "P50 ({{pod}})"
    }
   ]
  },
  {
   "title": "Items in the Queue",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "friendli_current_assigned_items",
     "legendFormat": "Processing ({{pod}})"
    },
    { "expr": "friendli_current_waiting_items", "legendFormat": "Waiting ({{pod}})" }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Failures",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(friendli_failure_by_cancel[$__rate_interval]) > 0",
     "legendFormat": "Cancel ({{pod}})"
    },
    {
     "expr": "rate(friendli_failure_by_timeout[$__rate_interval]) > 0",
     "legendFormat": "Timeout ({{pod}})"
    },
    {
     "expr": "rate(friendli_failure_by_nan_error[$__rate_interval]) > 0",
     "legendFormat": "NaN ({{pod}})"
    },
    {
     "expr": "rate(friendli_failure_by_reject[$__rate_interval]) > 0",
     "legendFormat": "Reject ({{pod}})"
    }
   ]
  },
  {
   "title": "Friendli TCache Hit Ratio",
   "type": "heatmap",
   "description": "Friendli TCache is a cache to reuse recurring computations. Learn more at https://friendli.ai/blog/friendli-tcache/",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (le) (rate(friendli_tcache_hit_ratio_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Input Token Length",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "sum by (le) (rate(friendli_input_lengths_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Output Token Length",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (le) (rate(friendli_output_lengths_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queueing Delays of Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "friendli_requests_queueing_delays{quantile=\"0.99\"}",
     "legendFormat": "P99 ({{pod}})"
    },
    {
     "expr": "friendli_requests_queueing_delays{quantile=\"0.9\"}",
     "legendFormat": "P90 {{pod}})"
    },
    {
     "expr": "friendli_requests_queueing_delays{quantile=\"0.5\"}",
     "legendFormat": "P50 ({{pod}})"
    }
   ]
  }
 ]
}