{
 "title": "Per-Pod View (Friendli Engine)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(friendli_engine_version,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (friendli_engine_version{pod=\"$pod\"})",
     "legendFormat": "Engine {{version}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(friendli_responses_total{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "friendli_requests_latencies{quantile=\"0.9\",pod=\"$pod\"}",
     "legendFormat": "P90 Latency"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "friendli_requests_ttft{quantile=\"0.9\",pod=\"$pod\"}",
     "legendFormat": "P90 TTFT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(friendli_current_assigned_items{pod=\"$pod\"})",
     "legendFormat": "Processing Items"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(friendli_current_waiting_items{pod=\"$pod\"})",
     "legendFormat": "Waiting Items"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Requests Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(friendli_requests_total{pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(friendli_responses_total{pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "Served"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "friendli_requests_latencies{quantile=\"0.99\",pod=\"$pod\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "friendli_requests_latencies{quantile=\"0.9\",pod=\"$pod\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "friendli_requests_latencies{quantile=\"0.5\",pod=\"$pod\"}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "friendli_requests_ttft{quantile=\"0.99\",pod=\"$pod\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "friendli_requests_ttft{quantile=\"0.9\",pod=\"$pod\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "friendli_requests_ttft{quantile=\"0.5\",pod=\"$pod\"}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Items in the Queue",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "friendli_current_assigned_items{pod=\"$pod\"}",
     "legendFormat": "Processing"
    },
    {
     "expr": "friendli_current_waiting_items{pod=\"$pod\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Failures",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(friendli_failure_by_cancel{pod=\"$pod\"}[$__rate_interval]) > 0",
     "legendFormat": "Cancel"
    },
    {
     "expr": "rate(friendli_failure_by_timeout{pod=\"$pod\"}[$__rate_interval]) > 0",
     "legendFormat": "Timeout"
    },
    {
     "expr": "rate(friendli_failure_by_nan_error{pod=\"$pod\"}[$__rate_interval]) > 0",
     "legendFormat": "NaN"
    },
    {
     "expr": "rate(friendli_failure_by_reject{pod=\"$pod\"}[$__rate_interval]) > 0",
     "legendFormat": "Reject"
    }
   ]
  },
  {
   "title": "Friendli TCache Hit Ratio",
   "type": "heatmap",
   "description": "Friendli TCache is a cache to reuse recurring computations. Learn more at https://friendli.ai/blog/friendli-tcache/",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (rate(friendli_tcache_hit_ratio_bucket{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Input Token Length",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (rate(friendli_input_lengths_bucket{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Output Token Length",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (rate(friendli_output_lengths_bucket{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queueing Delays of Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "friendli_requests_queueing_delays{quantile=\"0.99\",pod=\"$pod\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "friendli_requests_queueing_delays{quantile=\"0.9\",pod=\"$pod\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "friendli_requests_queueing_delays{quantile=\"0.5\",pod=\"$pod\"}",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}